### ISSUE TITLE
fzf can't use ctrl jk to selection if  set them with prefix to resize-pane

### ISSUE THREAD

**Issue by roachsinai** [sainnhe/tmux-fzf#11]
```
bind -n C-k resize-pane -U 7
bind -n C-j resize-pane -D 7
```

above setting enable, the trigger tmux-fzf, ctrl-j will resize the fzf pane not choose next entry.

**Comment by sainnhe** [comment]
The `-n` option will make the key bindings work without `prefix`, so your config will use `C-j` and `C-k` to resize panes.

To use `prefix` + `C-j`/`C-k` to resize pane, try this config:

```
bind-key -T prefix C-k resize-pane -U 7
bind-key -T prefix C-j resize-pane -D 7
```

**Comment by roachsinai** [comment]
非常感谢！

**Comment by sainnhe** [comment]
刚刚支持了popup window，你可以试试

**Comment by roachsinai** [comment]
emmm,通过AUR安装了tmux-git 并没有popup,我看readme说的是默认开启啊。

`local/tmux-git 8894_3.1b.r651.g04a1a84b-1`

**Comment by sainnhe** [comment]
我也是这个版本啊，不过可能得重启一下计算机才行。

另外现在可以强制启用了

`~/.tmux.conf`

```
TMUX_FZF_POPUP=1
```

**Comment by roachsinai** [comment]
嗯嗯，好用了！

**Comment by sainnhe** [comment]
顺便再安利一波，我刚刚又造了个轮子23333

https://github.com/sainnhe/tmux-translator

**Comment by roachsinai** [comment]
安利失败，因为韦大的那个我都没有用。不过可以翻译句子，是挺好的。
