### ISSUE TITLE
trigger tmux-fzf then press ESC got an warning

### ISSUE THREAD

**Issue by roachsinai** [sainnhe/tmux-fzf#12]
![image](https://user-images.githubusercontent.com/9500049/85408957-c94a4b80-b597-11ea-8b4b-c064386dfdb4.png)

**Comment by roachsinai** [comment]
What's more how to reverse fzf like pic in README.md?

I change setting to `TMUX_FZF_OPTIONS="--height 35% --reverse"`, got same warning above.

But `--reverse` works for `fzf-tmux`.

Thanks in advanced!

**Comment by sainnhe** [comment]
This should be fixed via f358fb7.

**Comment by roachsinai** [comment]
Fixed! Thanks.
