### ISSUE TITLE
Can I create a key binding to go right into fzf session attach?

### ISSUE THREAD

**Issue by axelson** [sainnhe/tmux-fzf#16]
I switch session a bunch and I'd like to be able to hit a single key binding to go right into choosing a session to switch to. It looks like right now I need to:
1. `prefix+F`
1. `session`
1. `attach`
1. Type session name/prefix

So instead I'd like to skip steps 2 and 3 (for this custom keybinding). Is that possible? I cannot find out how from looking at the documentation.

**Comment by sainnhe** [comment]
See [this](https://github.com/sainnhe/tmux-fzf/issues/6#issuecomment-578750879).

**Comment by axelson** [comment]
Thanks! That works great!
