### ISSUE TITLE
Window Switch (omit session name, show only current session windows)

### ISSUE THREAD

**Issue by tami5** [sainnhe/tmux-fzf#17]
Hi there, thanksssss sooooo much for this plugin and the other cool themes you have added.

I'm using tmux-fzf as a session and a window switcher, and I want to accomplish two things:

1. Omit session name from window switch 
2. Show only current session windows

My current settings
```
TMUX_FZF_WINDOW_FORMAT="#{window_name}"
TMUX_FZF_SESSION_FORMAT="#{session_name}"
```

session name is duplicated in session format

Thanks

**Comment by sainnhe** [comment]
Currently you can't hide session information in actions for windows, because some actions like `link` need it.

Sorry but I'm not interested in implementing this feature, you can fork this repo and implement it by yourself.

**Comment by tami5** [comment]
Thanks
