### ISSUE TITLE
Quickly jump to session->attach

### ISSUE THREAD

**Issue by nce** [sainnhe/tmux-fzf#31]
Hey, thanks for that great plugin. Been using it since a few days.

One thing is bogging me, i usually want to switch to different sessions. So i have to press <kbd>CTRL</kbd><kbd>b</kbd>, <kbd>Enter</kbd>, <kbd>Enter</kbd> just to select the session i want to switch to (session & attach are my defaults for these menues).

Is there a way to open instantly into the session->attach menue? And probably likewise to all other subcategories?

Thanks for your support!

**Comment by sainnhe** [comment]
Duplicated #6.
