### ISSUE TITLE
Feature Request: connect to attached sessions

### ISSUE THREAD

**Issue by axelson** [sainnhe/tmux-fzf#37]
I run multiple terminal emulators on different workspaces. Often I will want to switch to a tmux session that is already attached in a different workspace. It would be nice if this was supported by tmux-fzf, perhaps via an optional configuration.

**Comment by sainnhe** [comment]
Could you try to remove these two lines and see if it works for you?

https://github.com/sainnhe/tmux-fzf/blob/fba8b77f0f7042ff404c1f378c53f5232fc76a6d/scripts/session.sh#L28-L29

**Comment by axelson** [comment]
Yeah, that works great :+1:
