### ISSUE TITLE
Border and padding of popup window

### ISSUE THREAD

**Issue by argapost** [sainnhe/tmux-fzf#39]
Hello and thanks for this plugin!

When I launch the popup window I have an additional border and padding outside of the fzf like in the image below:
![image](https://user-images.githubusercontent.com/58076098/120002261-ede34a80-bfd4-11eb-917f-09a4d08a9764.png)

Is it possible to remove the outside border and padding? Thank you in advance!

**Comment by sainnhe** [comment]
Honestly I don't know, but I exposed related api, check [README](https://github.com/sainnhe/tmux-fzf#fzf-behavior).

So you may need to take a look at the man page of tmux and see if tmux provides related options for popup menu that can remove the border, if they exist, then you can use the above configuration option to customize its behavior.
