### ISSUE TITLE
TAB to mark multiple items not working

### ISSUE THREAD

**Issue by matthewdeancooper** [sainnhe/tmux-fzf#40]
When using session -> kill, pressing TAB does not mark any sessions.

**Comment by sainnhe** [comment]
Does tab works in command line fzf?

E.g.

```shell
ls | fzf
```

**Comment by matthewdeancooper** [comment]
Yep, tab is working correctly for all other FZF related scripts.

**Comment by sainnhe** [comment]
Should be fixed now.

**Comment by matthewdeancooper** [comment]
Nice one. Keep up the good work.
