### ISSUE TITLE
Removing prefixes for `TMUX_FZF_*_FORMAT`

### ISSUE THREAD

**Issue by toyboot4e** [sainnhe/tmux-fzf#47]
Currently, [session], [window] and [pane] formats are displayed after some prefix, like:

```sh
"#S:#{window_index}: $TMUX_FZF_WINDOW_FORMAT"
```

But then we can't remove session names even if we only want to see `${window_name}`.
So I suggest removing those prefixes for `TMUX_FZF_*_FORMAT` so that users get full control:

```sh
"$TMUX_FZF_WINDOW_FORMAT"
```

Thank you.

[session]: https://github.com/sainnhe/tmux-fzf/blob/master/scripts/session.sh#L10
[window]: https://github.com/sainnhe/tmux-fzf/blob/master/scripts/window.sh#L11
[pane]: https://github.com/sainnhe/tmux-fzf/blob/master/scripts/pane.sh#L12

**Comment by sainnhe** [comment]
The prefix is used as an identifier, this plugin need it to know the extract session/window/pane ID to switch to.

So in current implementation, it can't be removed.
