### ISSUE TITLE
Add a menu for pasting words from tmux

### ISSUE THREAD

**Issue by r-darwish** [sainnhe/tmux-fzf#50]
[This blog post](https://blog.plenz.com/2012-01/zsh-complete-words-from-tmux-pane.html) shows how to do it specifically for ZSH. Having this functionality in this plugin will make it usable in any CLI app.

**Comment by sainnhe** [comment]
Isn't the `clipboard` doing this?

**Comment by r-darwish** [comment]
Clipboard shows things that were already copied (probably using the mouse).
What I'm suggesting is a menu that will show all words that appear on tmux (with `tmux capture-pane` like in the blog post) and allows selecting one of these.
This way I can run `docker ps` and insert the ID of one of the container to a `docker rm` command without the need to copy it to the clipboard before.

**Comment by sainnhe** [comment]
So we can pipe the content of `$(tmux capture-pane -ep -t <target>)` to tmux-fzf and filter it, then what should we do with the filtered output?

The existing actions will execute certain commands with the output, for example we can kill a session via `tmux kill-session` command with the filtered output (the output is a target session).

But in your case, it looks like you'd like to execute a custom command such as `docker rm`.

IMO it might be better to write your own script to do this.

**Comment by r-darwish** [comment]
I think that just pasting the output to tmux will be generic enough, this way I can type `docker rm ` and then complete the ID

**Comment by sainnhe** [comment]
1. Your request can be done via a zsh completion func, my collection can exactly do this: https://github.com/sainnhe/zsh-completions
2. The filtered output will be an entire line, are you sure this is suitable to directly paste it to a pane?

Sorry but I still didn't get the point why we need this.

**Comment by r-darwish** [comment]
I'll try implementing it in a PR. Perhaps it will make more sense then
