### ISSUE TITLE
Toggle `pane switch` directly 

### ISSUE THREAD

**Issue by LintaoAmons** [sainnhe/tmux-fzf#55]
Now, I have to press the shortcuts, then goto `pane`, then goto `switch`, then I can see the panes, which is too mush typing.

- I want to have a shortcut to show the `switch pane` window directly.
    - ![image](https://user-images.githubusercontent.com/95092244/194700091-024aad5c-fa4a-4f10-81a9-5df6999289e1.png)

Can I do that?~

Maybe this could be like `k9s`.. display the pane first, then choose the actions against the selected pane?

Thanks for making this wonderful tool~~~~~

**Comment by sainnhe** [comment]
See this comment https://github.com/sainnhe/tmux-fzf/issues/6#issuecomment-578750879
