### ISSUE TITLE
How to shortcut menu

### ISSUE THREAD

**Issue by maxigit** [sainnhe/tmux-fzf#6]
I've just installed this plugin and it looks great.
However, I was wondering, is there a way to do preselect options so I can create a  key binding which for example allow me to attach a session without having to select `session` and then `attach` ?

**Comment by sainnhe** [comment]
This is a good idea, this feature is supported via 09e5e0b.

## Preselect `session`, `window` or `pane`

Simply bind a key to execute the shell script

```
bind-key "C-l" run-shell -b "/home/sainnhe/.tmux/plugins/tmux-fzf/scripts/session.sh"
```

All available shell scripts can be found in [`/path/to/tmux-fzf/scripts`](https://github.com/sainnhe/tmux-fzf/tree/master/scripts).

## Preselect action

Pass a parameter to the shell script:

```
bind-key "C-l" run-shell -b "/home/sainnhe/.tmux/plugins/tmux-fzf/scripts/session.sh attach"
```

Will execute `attach session`.

Available actions for each shell script:

- [session](https://github.com/sainnhe/tmux-fzf/blob/master/scripts/session.sh#L18)
- [window](https://github.com/sainnhe/tmux-fzf/blob/master/scripts/window.sh#L20)
- [pane](https://github.com/sainnhe/tmux-fzf/blob/master/scripts/pane.sh#L19)

## Add frequently used actions to the user menu

For example, in `~/.tmux.conf`:

```
TMUX_FZF_MENU=\
"attach session\n/home/sainnhe/.tmux/plugins/tmux-fzf/scripts/session.sh attach\n"\
"rename window\n/home/sainnhe/.tmux/plugins/tmux-fzf/scripts/window.sh rename\n"
```

will add `attach session` and `rename window` to the user menu.

**Comment by maxigit** [comment]
Brilliant! 
I add a binding to switch to any window (which is great because it allows to change session if needed) and it works perfectly. Many thanks!

**Comment by you-n-g** [comment]
@sainnhe It looks great!
I think it would be better if we could strip the time of the session list (Rarely people will select a session by time).
![image](https://user-images.githubusercontent.com/465606/127989605-7e375fef-e7ae-4f5c-9ea4-b7e0374f4262.png)

**Comment by zhengpd** [comment]
I think this should be added to the README. It's really helpful.

**Comment by zhengpd** [comment]
> @sainnhe It looks great!
> I think it would be better if we could strip the time of the session list (Rarely people will select a session by time).
> 
> 
> Thanks

@you-n-g You could hide the time with custom `TMUX_FZF_SESSION_FORMAT="#{session_name}"`

**Comment by you-n-g** [comment]
@zhengpd It works.
Thanks so much!

**Comment by shihabdider** [comment]
I'm getting a weird error where the tmux-fzf menu will come up (to attach to a new session) but hitting <enter> on any of the entries doesn't actually switch to that session.

I put the following in my .tmux.conf:

`bind-key "f" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh attach"`

Hitting `Prefix + f` will bring up the menu and I can filter it, but it won't actually switch to the selected session once I hit enter. This is true even if I run the script manually on the command line (`bash ~/.tmux/plugins/tmux-fzf/scripts/session.sh attach`). If I use the plugin normally via `F` and navigate to session -> switch, then it works.

**Comment by SpyMachine** [comment]
I'm seeing exactly the same as @shihabdider.

**Comment by ramytanios** [comment]
> I'm getting a weird error where the tmux-fzf menu will come up (to attach to a new session) but hitting on any of the entries doesn't actually switch to that session.
> 
> I put the following in my .tmux.conf:
> 
> `bind-key "f" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh attach"`
> 
> Hitting `Prefix + f` will bring up the menu and I can filter it, but it won't actually switch to the selected session once I hit enter. This is true even if I run the script manually on the command line (`bash ~/.tmux/plugins/tmux-fzf/scripts/session.sh attach`). Using the plugin normally via `F` and navigate to session -> switch, still works.

**Comment by ramytanios** [comment]
@shihabdider  I also have the same issue. Any solutions?

**Comment by shihabdider** [comment]
@ramytanios I just gave up on this plugin altogether because of this. I now use (the simpler, but working) https://github.com/siadat/session-finder

**Comment by tkamat** [comment]
@ramytanios use the new "switch" option instead of "attach" in the bind-key config:

`bind-key "C-l" run-shell -b "/home/sainnhe/.tmux/plugins/tmux-fzf/scripts/session.sh attach"`
