### ISSUE TITLE
`attach` sub command for session.sh

### ISSUE THREAD

**Issue by MahdiAghaei1** [sainnhe/tmux-fzf#62]
I have this line in my .tmux.conf
```sh
bind-key -r o run-shell "~/.tmux/plugins/tmux-fzf/scripts/session.sh \"attach\""
```
It used to work to directly open a pane including all the sessions and attach to the selected one.
After I updated the tmux plugins it does not work any more, it would open the pane but when I select a session it would do nothing. does the `attach` sub command got removed? How can I achieve same behavior with the current version?

**Comment by sainnhe** [comment]
It's renamed to "switch" now.
