### ISSUE TITLE
The fzf window has incomplete borders.

### ISSUE THREAD

**Issue by ImVeri** [sainnhe/tmux-fzf#68]
- OS: Manjaro KDE Plasma kernel 6.1.41-1-MANJARO
- Tmux version: tmux 3.3a
- Terminal emulator: yakuake(konsole), alacritty
- `echo $TERM`: screen.konsole-256color

### yakuake:
![Screenshot_20230731_132250](https://github.com/sainnhe/tmux-fzf/assets/49151698/62a9ed67-ecea-4466-a525-733bf2086a9f)
<br>
### alacritty:
![Screenshot_20230731_132632](https://github.com/sainnhe/tmux-fzf/assets/49151698/8777f2f0-8353-4c67-a2a3-f2fda2813b00)

**Comment by sainnhe** [comment]
I can't reproduce. Could you try the following command:

`ls | fzf-tmux -p`

**Comment by ImVeri** [comment]
![Screenshot_20230731_175257](https://github.com/sainnhe/tmux-fzf/assets/49151698/fd433a96-edf8-4aca-9f1d-3418102ebd3c)

**Comment by sainnhe** [comment]
`fzf-tmux` is a script provided by fzf. This seems like a bug of fzf, maybe you should report it to their repository instead.

**Comment by ImVeri** [comment]
好的
