### ISSUE TITLE
Support tmux session titles with non alphanumeric characters

### ISSUE THREAD

**Issue by HerveMARTIN** [sainnhe/tmux-fzf#7]
Attach session with a non alphanumeric name is not working.
For example : if I select a tmux session named 'private_dotfiles', I get this error : 
`.tmux/plugins/tmux-fzf/scripts/session.sh' returned 123`
I'll submit a PR soon, it's a regexp pb.

**Comment by sainnhe** [comment]
Thanks for your fix! This PR has been merged.
