### ISSUE TITLE
rename session seems to append to name, not rename

### ISSUE THREAD

**Issue by lushcluejug** [sainnhe/tmux-fzf#83]
I'm on tmux 3.2a

When I select [prefix-F], session, rename, [current], and enter the rename, I get a blank screen with the name I just typed in, and the session name is unchanged.

This implies that the input is being appended. Whatever the behaviour is, my session name is not being changed.

**Comment by sainnhe** [comment]
Could you try to checkout commit 4bcd8c7 and see if it work for you?
