### ISSUE TITLE
Session add or rename doesn't work

### ISSUE THREAD

**Issue by 3nd3r1** [sainnhe/tmux-fzf#84]
I'm using tmux 3.2a and renaming or creating new sessions doesn't work.
Caused by [Tmux command-prompt stdout issue](https://github.com/tmux/tmux/issues/2512).

**Comment by sainnhe** [comment]
Could you try to checkout commit 4bcd8c7 and see if it work for you?

**Comment by 3nd3r1** [comment]
It works. Why is this not in master?

**Comment by sainnhe** [comment]
Sorry for late reply. I' too busy recently :(

> Why is this not in master?

This feature is merged in https://github.com/sainnhe/tmux-fzf/pull/80

> Does using command-prompt work on some versions of Tmux?

I'm using tmux 3.4, and it works nicely.

The command prompt implementation has been replaced by fifo implementation in https://github.com/sainnhe/tmux-fzf/commit/1540cbfa5a6adcec57f373881b5b970f1ac1cae5 . This issue should be fixed now.
