### ISSUE TITLE
you cannot pass FZF OPTIONS to TMUX_FZF_OPTIONS

### ISSUE THREAD

**Issue by Gioyik** [sainnhe/tmux-fzf#9]
Hey,

This is a great plugin, I have been configuring it for a while and pretty impressed. I tried to push how much the plugin fzf window could be customized and I'm getting behavior that I don't expect. I understand this plugin somewhat depends on the params available in `fzf-tmux`, so if we check what available we get:

```
$ fzf-tmux --help                                                                                                     [I]
usage: fzf-tmux [-u|-d [HEIGHT[%]]] [-l|-r [WIDTH[%]]] [--] [FZF OPTIONS]

  Layout
    -u [HEIGHT[%]]  Split above (up)
    -d [HEIGHT[%]]  Split below (down)
    -l [WIDTH[%]]   Split left
    -r [WIDTH[%]]   Split right

    (default: -d 50%)

```

it says you can pass normal fzf options to `fzf-tmux`, so if I run the following command:

```
fzf-tmux -d 25% --prompt=. --color=dark --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7
```

I get an fzf window with changes I set as options in the command, however, when you try to add those to the `TMUX_FZF_OPTIONS` like this:

```
TMUX_FZF_OPTIONS="-d 25% --prompt=. --color=dark --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7"
```

But I get an error:

```'/Users/gioyik/.tmux/plugins/tmux-fzf/scripts/.sh' returned 127```

Not sure if I'm doing it correctly or something is not being parsed correctly inside the plugin.

**Comment by sainnhe** [comment]
Sorry for late reply, this should be fixed via f358fb7.
