### ISSUE TITLE
feature request: add ability to style fzf popup border

### ISSUE THREAD

**Issue by blacktop** [sainnhe/tmux-fzf#91]
I've created an issue here as well: 
- https://github.com/omerxx/tmux-sessionx/issues/135
- https://github.com/junegunn/fzf/issues/3973

I suppose since you use the official tmux-fzf if installed (if/when they add it it'll be auto added here as well)

Thanks!

**Comment by sainnhe** [comment]
PR is welcome

**Comment by blacktop** [comment]
fzf author told me that I should use fzf --tmux as fzf-tmux was deprecated
